name: chat_demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.9

  # utilities
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  country_picker: ^2.0.19
  image_picker: ^0.8.6
  flutter_contacts: ^1.1.5+1
  # file_picker: ^5.2.4
  uuid: ^3.0.7
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.3
  emoji_picker_flutter: ^1.5.1
  # enough_giphy_flutter: ^0.3.0 # This is package deprecated Platform buttons
  giphy_get: ^3.2.0
  flutter_sound: ^9.2.13
  audioplayers: ^1.1.1
  swipe_to: ^1.0.2

  # riverpod - state management and providers
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/backgroundImage.png
    - assets/images/landing-bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
